### PR TITLE
add Grafana dashboard

### PR DESCRIPTION
**Pull request by Teelevision**
Add a template for a Grafana dashboard that uses the Prometheus metrics.

### CODE REVIEW

**Comment by Teelevision** [comment]
@threez wants some graph for the number of rows affected/returned (Postgres)

**Comment by Teelevision** [comment]
@threez added all metrics

**Comment by threez** [comment]
@Teelevision hey, we need to change the datasource to be a variable as well, see https://www.robustperception.io/switching-between-prometheus-servers-in-grafana-using-data-source-variables

**Comment by threez** [comment]
We should have more detailed graphs that explain our api requests better. We should not use `Hz` for requests counts as this is a very unusual way of talking about the data.

**Comment by Teelevision** [comment]
> @Teelevision hey, we need to change the datasource to be a variable as well, see https://www.robustperception.io/switching-between-prometheus-servers-in-grafana-using-data-source-variables

Done. Also added variable for the database. And made the namespace and job variables configurable.

> We should have more detailed graphs that explain our api requests better. We should not use `Hz` for requests counts as this is a very unusual way of talking about the data.

Updated existing graphs. Added metrics for object storage and circuit breakers:
image

**Comment by Teelevision** [comment]
@threez need any more graphs?

**Comment by Teelevision** [comment]
@threez this now includes the latest changes

**Comment by threez** [comment]
Awesome job, thx.

**Pull request merged**
